version: '3.7'
services:
    application:
        image: richcongress/php:8.0-fpm
        volumes:
            - .:/app:rw,cached
            - ~/.composer:/home/application/.composer:cached
            - ~/.ssh:/home/application/.ssh:cached
