:toc: macro
:toc-title:
:toclevels: 2
:sectnums:
:sectnumlevels: 2

image:https://img.shields.io/packagist/v/NicolasGuilloux/phpunit-dependency-injection-bundle[link="https://packagist.org/packages/NicolasGuilloux/phpunit-dependency-injection-bundle",window="_blank"]
image:https://github.com/NicolasGuilloux/phpunit-dependency-injection-bundle/workflows/Tests/badge.svg[link="https://github.com/NicolasGuilloux/phpunit-dependency-injection-bundle/actions",window="_blank"]
image:https://coveralls.io/repos/github/NicolasGuilloux/phpunit-dependency-injection-bundle/badge.svg?branch=master[link="https://coveralls.io/github/NicolasGuilloux/phpunit-dependency-injection-bundle?branch=master",window="_blank"]
image:https://api.codeclimate.com/v1/badges/e919cdfbba03e591a67e/maintainability[link="https://codeclimate.com/github/NicolasGuilloux/phpunit-dependency-injection-bundle/maintainability",window="_blank"]
image:https://img.shields.io/badge/contributions-welcome-brightgreen.svg?style=flat[link="https://github.com/NicolasGuilloux/phpunit-dependency-injection-bundle/issues",window="_blank"]
image:https://img.shields.io/badge/license-MIT-blue.svg[link="LICENSE",window="_blank"]
image:https://img.shields.io/badge/PHP-7.3%2B-yellow[]
image:https://img.shields.io/badge/Symfony-4%2B-black[]
image:https://img.shields.io/badge/Symfony-5%2B-black[]


Short description


[discrete]
== Table of content

toc::[]


== Installation

Execute the composer command to install the bundle:

[source,bash]
----
composer require nicolasguilloux/phpunit-dependency-injection-bundle --dev
----

Now add the configuration for the test environment and change it to your needs:

[source,yaml]
----
phpunit_dependency_injection:
    tests_namespace: 'App\Tests'
----

Now, it is just a matter of implementing the trait in the corresponding test in the `setUp` method.

Warning: Note that the class is still a TestCase, so you won't be able to use the constructor to inject dependencies. This is where the `Required` annotation/attribute becomes handy. Checkout the link:https://symfony.com/doc/current/service_container/calls.html[Symfony's documentation^].

[source,php]
----
use NicolasGuilloux\PhpunitDependencyInjectionBundle\TestCase\AutowiringTestTrait;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Contracts\Service\Attribute\Required;

final class RandomTest extends KernelTestCase
{
    use AutowiringTestTrait;

    #[Required]
    public LoggerInterface $logger;

    public function setUp(): void
    {
        parent::setUp();

        self::bootKernel();
        $this->autowire(self::getContainer());
    }

    public function testSomething(): void
    {
        self::assertInstanceOf(LoggerInterface::class, $this->logger);
    }
}
----

== Motivations

Checkout the link:./docs/Motivations.adoc[Motivations article].

== Documentation

=== link:docs/Configuration.adoc[Configuration]


== Versioning

phpunit-dependency-injection-bundle follows link:https://semver.org/[semantic versioning^]. In short the scheme is MAJOR.MINOR.PATCH where
1. MAJOR is bumped when there is a breaking change,
2. MINOR is bumped when a new feature is added in a backward-compatible way,
3. PATCH is bumped when a bug is fixed in a backward-compatible way.

Versions bellow 1.0.0 are considered experimental and breaking changes may occur at any time.


== Contributing

Contributions are welcomed! There are many ways to contribute, and we appreciate all of them. Here are some of the major ones:

* link:https://github.com/NicolasGuilloux/phpunit-dependency-injection-bundle/issues[Bug Reports^]: While we strive for quality software, bugs can happen, and we can't fix issues we're not aware of. So please report even if you're not sure about it or just want to ask a question. If anything the issue might indicate that the documentation can still be improved!
* link:https://github.com/NicolasGuilloux/phpunit-dependency-injection-bundle/issues[Feature Request^]: You have a use case not covered by the current api? Want to suggest a change or add something? We'd be glad to read about it and start a discussion to try to find the best possible solution.
* link:https://github.com/NicolasGuilloux/phpunit-dependency-injection-bundle/pulls[Pull Request^]: Want to contribute code or documentation? We'd love that! If you need help to get started, GitHub as link:https://help.github.com/articles/about-pull-requests/[documentation^] on pull requests. We use the link:https://help.github.com/articles/about-collaborative-development-models/["fork and pull model"^] were contributors push changes to their personal fork and then create pull requests to the main repository. Please make your pull requests against the `master` branch.

As a reminder, all contributors are expected to follow our link:./CODE_OF_CONDUCT.md[Code of Conduct].


== License

phpunit-dependency-injection-bundle is distributed under the terms of the MIT license.

See link:./LICENSE[LICENSE] for details.


== Hacking

You might use Docker and `docker-compose` to hack the project. Check out the following commands.

[source,bash]
----
# Start the project
docker-compose up -d

# Install dependencies
docker-compose exec application composer install

# Run tests
docker-compose exec application bin/phpunit

# Run a bash within the container
docker-compose exec application bash
----
